#!/usr/bin/env python3
# SPDX-License-Identifier: Unlicense OR 0BSD
"""Compile cobs.c + js/shim.c to wasm and emit the JS module that inlines it.

Everything written lands under build/. js/ stays hand-written source only.
Standard library only, like release.py.
"""

import argparse
import base64
import pathlib
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[2]
BUILD = ROOT / "build"
WASM_OUT = BUILD / "wasm" / "cobs.wasm"        # intermediate, kept for inspection
JS_OUT = BUILD / "js" / "src" / "wasm.js"      # staged into the package tree

# -mcpu=mvp pins the feature floor; clang's default 'generic' CPU gains features
#   across releases. Byte-identical for this code today.
# --no-default-config skips wasi-sdk's clang.cfg and the --sysroot it injects.
# No --allow-undefined: a link error is how we learn something reached for libc.
# --stack-first puts the shadow stack below data, so overflow traps out of bounds.
CFLAGS = [
    "--target=wasm32-unknown-unknown", "--no-default-config",
    "-std=c99", "-DNDEBUG", "-mcpu=mvp",
    "-ffreestanding", "-nostdlib", "-fvisibility=hidden",
    "-Wall", "-Wextra", "-Werror", "-Wconversion",
    "-I", str(ROOT),
]
LDFLAGS = [
    "-Wl,--no-entry", "-Wl,--stack-first", "-Wl,-z,stack-size=8192",
    "-Wl,--export-memory", "-Wl,--strip-all",
]


def build(cc, opt, initial_memory, word_bits, out):
    cmd = [cc, *CFLAGS, opt, f"-Wl,--initial-memory={initial_memory}"]
    if word_bits:
        cmd.append(f"-DCOBS_SWAR_WORD_BITS={word_bits}")
    cmd += [*LDFLAGS, "-o", str(out), str(ROOT / "cobs.c"), str(ROOT / "js" / "shim.c")]
    print("> " + " ".join(cmd))
    subprocess.run(cmd, check=True)


def emit_js(wasm_bytes, abi_version):
    b64 = base64.b64encode(wasm_bytes).decode("ascii")
    return (
        "// SPDX-License-Identifier: Unlicense OR 0BSD\n"
        "//\n"
        "// GENERATED by js/tools/build_wasm.py from cobs.c + js/shim.c. Do not edit.\n"
        "// Never committed; `make js-wasm` remakes it.\n"
        "//\n"
        "// Inlined rather than a separate .wasm, so there is no file to load: no fs,\n"
        "// no fetch, no bundler plugin, no async init.\n"
        "\n"
        f"export const WASM_ABI_VERSION = {abi_version};\n"
        f"export const WASM_BYTE_LENGTH = {len(wasm_bytes)};\n"
        f'export const WASM_BASE64 =\n  "{b64}";\n'
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cc", default=str(ROOT / "bin" / "wasm32-clang"))
    ap.add_argument("--opt", default="-O3")
    ap.add_argument("--word-bits", type=int, default=0,
                    help="override COBS_SWAR_WORD_BITS; 0 lets cobs.c choose (64 on wasm)")
    ap.add_argument("--initial-memory", type=int, default=262144,
                    help="4 pages; a 20 KiB payload needs ~41 KiB of arena")
    ap.add_argument("--size-max", type=int, required=True)
    args = ap.parse_args()

    with tempfile.TemporaryDirectory() as td:
        staged = pathlib.Path(td) / "cobs.wasm"
        build(args.cc, args.opt, args.initial_memory, args.word_bits, staged)

        inspect = [sys.executable, str(ROOT / "js" / "tools" / "wasm_inspect.py"),
                   str(staged), "--size-max", str(args.size_max),
                   "--initial-pages", str(args.initial_memory // 65536)]
        if subprocess.run(inspect).returncode:
            return 1

        wasm = staged.read_bytes()
        js = emit_js(wasm, abi_version=1)

        WASM_OUT.parent.mkdir(parents=True, exist_ok=True)
        WASM_OUT.write_bytes(wasm)
        JS_OUT.parent.mkdir(parents=True, exist_ok=True)
        JS_OUT.write_text(js)
        print(f"  wrote {JS_OUT.relative_to(ROOT)} "
              f"({len(js)} B) and {WASM_OUT.relative_to(ROOT)} ({len(wasm)} B)")
        return 0


if __name__ == "__main__":
    sys.exit(main())
