// SPDX-License-Identifier: Unlicense OR 0BSD
//
// Golden vectors produced by the C itself (js/tools/vectors_main.cc, regenerated by
// `make js-vectors`). This pins the package to cobs.c's exact bytes and error codes;
// everything else here compares JavaScript against JavaScript.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import * as cobs from '../src/index.js';

const vectors = JSON.parse(
  readFileSync(new URL('./vectors.json', import.meta.url), 'utf8'));

const b64 = (s) => new Uint8Array(Buffer.from(s, 'base64'));

test('golden vectors: the corpus is actually populated', () => {
  assert.ok(vectors.encode.length > 400,
    `expected a broad corpus, got ${vectors.encode.length} encode vectors`);
  assert.ok(vectors.decode_errors.length >= 10);
  const shapes = new Set(vectors.encode.map(v => v.shape));
  assert.ok(shapes.size >= 18, `expected every shape, got ${shapes.size}`);
});

test('golden vectors: encode matches the C byte for byte', () => {
  for (const v of vectors.encode) {
    const payload = b64(v.payload);
    assert.equal(payload.length, v.len, `${v.shape}/${v.len}: payload length`);
    assert.deepEqual(cobs.encode(payload), b64(v.frame), `${v.shape}/${v.len}`);
  }
});

test('golden vectors: decode recovers the C payload byte for byte', () => {
  for (const v of vectors.encode) {
    assert.deepEqual(cobs.decode(b64(v.frame)), b64(v.payload), `${v.shape}/${v.len}`);
  }
});

test('golden vectors: encodeMax bounds every frame the C produced', () => {
  for (const v of vectors.encode) {
    assert.ok(b64(v.frame).length <= cobs.encodeMax(v.len), `${v.shape}/${v.len}`);
  }
});

test('golden vectors: malformed frames are rejected', () => {
  // Each frame carries the C's verdict. The JS may reject earlier, since its
  // delimiter check runs first, so the contract is that it never accepts.
  for (const v of vectors.decode_errors) {
    const frame = b64(v.frame);
    if (v.ret === 'SUCCESS') continue;
    assert.throws(() => cobs.decode(frame),
      (e) => cobs.CobsError.isCobsError(e),
      `frame ${[...frame]} : C said ${v.ret}, JS accepted it`);
  }
});
